=== ferrestorresantoniomiguel/Stem-Personal/1DAM-Lenguajes-de-Marcas/T1/Ejercicios/Practicas_para_Examen/EjerciciosRepasoXSD/ej6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inventario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" />
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="categoria">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Periférico" />
                                        <xs:enumeration value="Ordenador" />
                                        <xs:enumeration value="Móvil" />
                                        <xs:enumeration value="Accesorio" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="precio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:pattern value="\d+\.\d{2}" />
                                        <xs:minInclusive value="0.01" />
                                        <xs:maxInclusive value="9999.99" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="stock">
                                <xs:simpleType>
                                    <xs:restriction base="xs:positiveInteger">
                                        <xs:minInclusive value= "1" />
                                        <xs:maxInclusive value="1000" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="proovedor" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" />
                                        <xs:element name="telefono">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[0-9]{3}-[0-9]{3}-[0-9]{3}" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="país" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" use="required" type="xs:positiveInteger" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ferrestorresantoniomiguel/Stem-Personal/1DAM-Lenguajes-de-Marcas/Ejercicios/Practicas_para_Examen/EjerciciosRepasoXSD/ej6.xml
<?xml version="1.0" encoding="UTF-8"?>
<inventario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ej6.xsd">
    <producto id="1">
        <nombre>PC Master</nombre>
        <categoria>Ordenador</categoria>
        <precio>2000.23</precio>
        <stock>200</stock>
        <proovedor>
            <nombre>Pccomponentes</nombre>
            <telefono>953-122-234</telefono>
            <país>España</país>
        </proovedor>
    </producto>
    <producto id="2">
        <nombre>PC Master</nombre>
        <categoria>Móvil</categoria>
        <precio>999.99</precio>
        <stock>1000</stock>
        <proovedor>
            <nombre>Pccomponentes</nombre>
            <telefono>953-122-234</telefono>
            <país>España</país>
        </proovedor>    
    </producto>

</inventario>
